name: smart_scan
description: "SmartScan is a mobile application that allows you to scan physical
  documents with professional quality from your camera. It uses automatic edge
  detection, image enhancement, offline OCR and PDF export, all with a smooth,
  secure and offline-first user experience."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  camera: ^0.11.1
  equatable: ^2.0.7
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  formz: ^0.8.0
  get_it: ^8.0.3
  go_router: ^15.1.3
  google_fonts: ^6.2.1
  google_mlkit_text_recognition: ^0.15.0
  hydrated_bloc: ^10.0.0
  image: ^4.5.4
  image_picker: ^1.1.2
  intl: any
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.1
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^30.1.37

dev_dependencies:
  bloc_test: ^10.0.0
  change_app_package_name: ^1.4.0
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Flavors Environments
    - flavors/.env.dev
    - flavors/.env.staging
    - flavors/.env.prod
    # Assets
    - assets/app-icon/
    - assets/loaders/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/images/introduction/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf

flutter_native_splash:
  color: "#6750A4"
  color_dark: "#2A292D"
  image: "assets/app-icon/native_splash_icon.png"

  android_12:
    color: "#6750A4"
    color_dark: "#2A292D"
    image: "assets/app-icon/native_splash_icon.png"
    # branding: "assets/app-icon/native_splash_icon.png"
